// Regenerates docs/URL-MIGRATION.md from src/data/redirects.mjs and the built sitemap.
// Usage: npm run build && node scripts/build-url-doc.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { legacyRedirects } from '../src/data/redirects.mjs';

const root = (p) => fileURLToPath(new URL(`../${p}`, import.meta.url));
const sitemap = readFileSync(root('dist/sitemap-0.xml'), 'utf8');
const urls = [...sitemap.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => m[1].replace('https://www.saasnova.ai', '') || '/');
const tick = (s) => '`' + s + '`';
const rows = Object.entries(legacyRedirects)
  .map(([from, to]) => `| ${tick(from)} (and ${tick(from + '.html')}) | ${tick(to)} |`)
  .join('\n');

const doc = `# URL migration and redirects

_Generated by \`scripts/build-url-doc.mjs\`. Edit \`src/data/redirects.mjs\`, then regenerate._

## New URL scheme

Clean, lowercase, hyphenated paths with no \`.html\` and no trailing slash, grouped by section:
\`/programs/*\`, \`/solutions/*\`, \`/solutions/*\`, \`/partners/*\`, \`/community/*\`, \`/insights/*\`, \`/news/*\`,
\`/case-studies/*\`, \`/campaigns/*\`, \`/events/*\`. Canonical host: \`https://www.saasnova.ai\`. Every page emits a
canonical tag that matches its clean URL, and the sitemap uses the same form.

Indexable pages (${urls.length}, from the generated sitemap):

${urls.map((u) => `- ${tick(u)}`).join('\n')}

Also published but kept out of the sitemap: \`/privacy\` and \`/terms\` (noindex, matching the legacy robots
policy), \`/404\`, \`/insights/rss.xml\`, \`/llms.txt\`, \`/llms-full.txt\`, \`/robots.txt\`, \`/assistant-kb.json\`.

## How redirects work on S3 + CloudFront

S3 does not read the legacy \`_redirects\` file (that is a Netlify / Cloudflare Pages format), and the
legacy 404.html JavaScript redirect is invisible to search engines. The new site uses a **CloudFront
Function** on viewer request, generated at build time from \`src/data/redirects.mjs\` into
\`deploy/cloudfront-function.js\`:

1. \`saasnova.ai/*\` to \`https://www.saasnova.ai/*\` (301)
2. Legacy paths, with or without \`.html\`, in any letter case, to the new URL (301). Query strings,
   including UTM parameters, are preserved.
3. \`/about/\` and \`/about/index.html\` to \`/about\` (301)
4. Any other \`/x.html\` to \`/x\` (301)
5. \`/programs/ignite\` is served internally from \`/programs/ignite/index.html\` (no redirect)

\`npm run test:edge\` runs 21 cases against the generated function, including \`/press&media.html\`
and \`/press%26media.html\`.

## Legacy to new (301)

| Legacy URL | New URL |
|---|---|
${rows}

Legacy pages whose path did not change (\`/about\`, \`/services\`, \`/partners\`, \`/careers\`, \`/contact\`,
\`/support\`, \`/privacy\`, \`/terms\`, \`/newsletter\`, \`/show\`, \`/fq-source\`) redirect from their \`.html\`
form to the clean URL.

## Migration checklist and risks

- **Back up** the current bucket (enable versioning or copy to a backup prefix) before the first deploy.
- **Attach the CloudFront Function before or with the first deploy.** \`deploy.ps1\` uses \`--delete\`, which
  removes the legacy \`.html\` objects. Their URLs keep working only because the function redirects them
  before the request reaches S3.
- **Search Console**: verification is preserved (\`/google960def4cf195e9cf.html\` is kept, and the
  \`google-site-verification\` meta tag is on every page). After launch, submit
  \`https://www.saasnova.ai/sitemap-index.xml\` and inspect the top legacy URLs.
- **Expect** a short ranking fluctuation while Google processes the 301s. Watch the Search Console
  "Pages" report for 404s for 2 to 4 weeks and add any missing legacy paths to \`redirects.mjs\`.
- **AWS Marketplace listings** link to \`/\`, \`/contact\` and \`/support\`, which all still resolve. Consider
  pointing each listing's resources at its own page (for example \`/programs/ignite\`).
- **Case studies moved** from \`/case-study-*\` to \`/case-studies/*\`, because the work was delivered during
  Jen Dawson's AWS tenure (see STRATEGY.md).
- After launch, delete the legacy \`_redirects\`, \`.nojekyll\` and the 404.html redirect script from the repo.
`;
writeFileSync(root('docs/URL-MIGRATION.md'), doc);
console.log(`docs/URL-MIGRATION.md written (${urls.length} pages, ${Object.keys(legacyRedirects).length} redirects)`);
